name: Deploy AWS

concurrency:
  group: livechat-deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: livechat-backend
  ECS_CLUSTER: livechat-cluster
  ECS_SERVICE: livechat-service
  TF_DIR: infra/

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker Image (SHA and latest)
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}
          docker tag $ECR_REPOSITORY:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image (SHA and latest)
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Save Image URI for Next Jobs
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}" >> $GITHUB_ENV

  terraform_and_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache Terraform Modules
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_DIR }}/.terraform
          key: terraform-${{ env.TF_DIR }}-${{ hashFiles(format('{0}/**.tf', env.TF_DIR)) }}
          restore-keys: |
            terraform-${{ env.TF_DIR }}-

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        working-directory: ${{ env.TF_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan and Apply
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform plan -var="image_uri=${{ env.IMAGE_URI }}" -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment

      - name: Notify Google Chat (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d "{\"text\":\"✅ Deploy completed successfully for service $ECS_SERVICE!\"}" \
            "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Notify Google Chat (Failure)
        if: failure()
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            MSG="✅ Deploy completed successfully for service $ECS_SERVICE!"
          else
            MSG="❌ Deployment failed for service $ECS_SERVICE!"
          fi
          curl -X POST -H 'Content-Type: application/json' \
            -d "{\"text\":\"❌ Deployment failed for service $ECS_SERVICE!\"}" \
            "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Destroy Infrastructure
        run: terraform destroy